config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  # root to: 'categories#index'
  
  resources :categories do
    resources :tasks
    # do
    # collection do
    #   get 'due_today'
    # end

    # for this category lang
  end
  get "/tasks/due_today", to: "tasks#due_today"
  # di na need ng category id kasi di naman to kasali sa nested routes
  # nil ang value ng params[:category_id] dito kasi wala naman params na category id yung route na to
  get "/tasks/backlog", to: "tasks#backlog"
end

app/models/task.rb
class Task < ApplicationRecord
  # Association
  belongs_to :category
  belongs_to :user
  

  # Validation
  validates :task_name, presence: true
  validates :task_body, presence: true
  validates :deadline, presence: true
  validates :status, presence: true
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  
  # before action
  before_action :authenticate_user!
  before_action :get_category, except: [:due_today, :backlog]
  before_action :get_task, only: [:show, :edit, :update, :destroy]

  # def today
  # @tasks = current_user.tasks.where(deadline: Date.today)
  # end

  def due_today
    # @tasks = @category.tasks.where(deadline: Date.today)
    if params[:sort] == "due_today_ongoing"
      @tasks = current_user.tasks.where(deadline: Date.current).order('status ASC').and(current_user.tasks.where(status: "On-going"))
    elsif params[:sort] == "due_today_pending"
      @tasks = current_user.tasks.where(deadline: Date.current).order('status ASC').and(current_user.tasks.where(status: "Pending"))
    else
      @tasks = current_user.tasks.where(deadline: Date.current).order('status ASC').and((current_user.tasks.where(status: "Pending")).or((current_user.tasks.where(status: "On-going"))))
    # redirect_to tasks_due_today_path
    end
  end

  def backlog
    # byebug
    if params[:sort] == "backlog_ongoing"
      @tasks = current_user.tasks.where('deadline < ?', Date.current).order('status ASC').and(current_user.tasks.where(status: "On-going"))
    elsif params[:sort] == "backlog_pending"
      @tasks = current_user.tasks.where('deadline < ?', Date.current).order('status ASC').and(current_user.tasks.where(status: "Pending"))
    else
      @tasks = current_user.tasks.where('deadline < ?', Date.current).order('status ASC').and((current_user.tasks.where(status: "Pending")).or((current_user.tasks.where(status: "On-going"))))
    end
  end

  def index
    @category_id = params[:category_id]
    if params[:sort] == "task_status"
      @tasks = @category.tasks.order('status ASC')
      # @tasks = current_user.categories.find(params[:category_id]).tasks.order('status ASC')
      # @tasks = Category.find(params[:category_id]).tasks.order('status ASC')
    elsif params[:sort] == "specific_category_tasks_today"
      @tasks = @category.tasks.where(deadline: Date.current).and((@category.tasks.where(status: "Pending")).or((@category.tasks.where(status: "On-going"))))
    elsif params[:sort] == "specific_category_tasks_pending"
      @tasks = @category.tasks.order('deadline ASC').where(status: "Pending")
    elsif params[:sort] == "specific_category_tasks_ongoing"
      @tasks = @category.tasks.order('deadline ASC').where(status: "On-going")
    elsif params[:sort] == "specific_category_tasks_done"
      @tasks = @category.tasks.order('deadline ASC').where(status: "Done")
    else
      @tasks = @category.tasks.order('deadline ASC')
      # @tasks = current_user.categories.find(params[:category_id]).tasks
      # @tasks = Category.find(params[:category_id]).tasks      
    end
  end


  def show
    # @task = Task.find(params[:id])
    # query buong task table, no assurance na sa specific category siya

    # @task = @category.tasks.find(params[:id])
    # alam niya na yung specific category
  end

  def new
    @task = @category.tasks.build
  end

  def create
    @task = @category.tasks.build(task_params)

    if @task.save
      redirect_to category_tasks_path, notice: 'Task was successfully created.'
    else
      render :new
    end
  end

  def edit
    # @task = Task.find(params[:id])
    # @task = current_user.tasks.find(params[:id])
  end

  def update
    # @task = Task.find(params[:id])
    # @task = current_user.tasks.find(params[:id])

    if @task.update(task_params)
      redirect_to category_tasks_path, notice: 'Task was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # @task = Task.find(params[:id])
    # @task = current_user.tasks.find(params[:id])

    @task.destroy
    redirect_to category_tasks_path, notice: 'Task was successfully deleted.'
  end

  private

  def get_category
    # @category = Category.find(params[:category_id])
    @category = current_user.categories.find(params[:category_id])
  end

  def get_task
    @task = @category.tasks.find(params[:id])
    # SELECT tasks.* FROM tasks
    # WHERE task.category_id = 5
    # AND tasks.id = 2
  end

  def task_params
    params.require(:task).permit(:task_name, :task_body, :deadline, :status).merge(user_id: current_user.id)
    # :category_id, :user_id,
  end
end


# console
# Task.where(deadline: Date.today)
# @tasks = Task.where(deadline: Date.today)
# @tasks - Task.where('deadline > ?', Date.yesterday)

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/tasks/backlog.html.erb
<h1> All Tasks: Backlogs </h1>

<table class="table table-bordered table-hover">
   <thead class="table-dark">
    <tr>
      <th class="text-nowrap"> Task </th>
      <th class="text-nowrap"> Details </th>
      <th class="text-nowrap"> Date Created </th>
      <th class="text-nowrap"> Date Updated </th>
      <th class="text-nowrap"> Deadline  </th>
      <th class="text-nowrap"> Status </th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <% if task.user == current_user %>
      <tr>
        <td class="text-nowrap"> <%= link_to task.task_name, category_task_path(task.category_id, task.id) %> </td>
        <td> <%= task.task_body%> </td>
        <td class="text-nowrap"> <%= task.created_at %> </td>
        <td class="text-nowrap"> <%= task.updated_at %> </td>
        <td class="text-nowrap"> <%= task.deadline %> </td>
        <td class="text-nowrap"> <%= task.status %> </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>




<p>
  <button class="btn btn-outline-dark btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Sort Tasks
  </button>
  <%= link_to "View All Backlogs", tasks_backlog_path, class:"btn btn-outline-dark btn-sm" %>
  <%= link_to "View All Categories", categories_path, class: "btn btn-outline-dark btn-sm" %>
</p>
<div class="collapse" id="collapseExample">
    <ul class="list-group">
      <li class="list-group-item text-nowrap"> <%= link_to "View Backlogs with On-going Status", :sort => "backlog_ongoing" %> </li>
      <li class="list-group-item text-nowrap"> <%= link_to "View Backlogs with Pending Status", :sort => "backlog_pending" %> </li>
    </ul>
</div>



<br/>

app/views/tasks/due_today.html.erb
<h1> All Tasks: Due Today </h1>

<table class="table table-bordered table-hover">
   <thead class="table-dark">
    <tr>
      <th class="text-nowrap"> Task </th>
      <th class="text-nowrap"> Details </th>
      <th class="text-nowrap"> Date Created </th>
      <th class="text-nowrap"> Date Updated </th>
      <th class="text-nowrap"> Deadline  </th>
      <th class="text-nowrap"> Status </th>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <% if task.user == current_user %>
      <tr>
        <td class="text-nowrap"> <%= link_to task.task_name, category_task_path(task.category_id, task.id) %> </td>
        <td> <%= task.task_body%> </td>
        <td class="text-nowrap"> <%= task.created_at %> </td>
        <td class="text-nowrap"> <%= task.updated_at %> </td>
        <td class="text-nowrap"> <%= task.deadline %> </td>
        <td class="text-nowrap"> <%= task.status %> </td>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>




<p>
  <button class="btn btn-outline-dark btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Sort Tasks
  </button>
  <%= link_to "View All Tasks Today", tasks_due_today_path, class:"btn btn-outline-dark btn-sm"  %>
  <%= link_to "View All Categories", categories_path, class: "btn btn-outline-dark btn-sm" %>
</p>

<div class="collapse" id="collapseExample">
    <ul class="list-group">
      <li class="list-group-item text-nowrap"> <%= link_to "View All Tasks with On-going Status", :sort => "due_today_ongoing" %> </li>
      <li class="list-group-item text-nowrap"> <%= link_to "View All Tasks with Pending Status", :sort => "due_today_pending" %> </li>
    </ul>
</div>

<br/>

app/views/tasks/edit.html.erb
<%=  form_with scope: :task, url: category_task_path, method: :put, locale: true do |form| %>


  <div class="card">
    <div class="card-header">
      <h1>Edit Task Details</h1>
    </div>
    <div class="card-body">
      <div class="field form-group">
        <%= form.label :task_name %>
        <%= form.text_field :task_name, class:"form-control" %>
      </div><br/>

      <div class="field form-group">
        <%= form.label :task_body %>
        <%= form.text_field :task_body, class:"form-control" %>
      </div><br/>

      <div class="field form-group">
        <%= form.label :deadline %>
        <%= form.date_field :deadline, class: "form-control" %>
      </div><br/>

      <div class="field form-group">
        <%= form.label :"Status" %>
        <div class="form-check">
          <%= form.radio_button :status, 'Pending' %>
          <%= form.label :"Pending", class: "form-check-label", for: "flexRadioDefault1" %>
        </div>

        <div class="form-check">
          <%= form.radio_button :status, 'On-going' %>
          <%= form.label :"On-going", class: "form-check-label", for: "flexRadioDefault1" %>
        </div>

        <div class="form-check">
          <%= form.radio_button :status, 'Done' %>
          <%= form.label :"Done", class: "form-check-label", for: "flexRadioDefault1" %>
        </div>
      </div><br/>

      <div class="actions">
        <%= form.submit "Save Changes", class: "btn btn-dark btn-sm" %>
        <%= link_to "Delete Task", category_task_path(@task.category_id, @task.id), method: :delete, :data => {:confirm => 'Are you sure you want to delete this task?'}, class: "btn btn-danger btn-sm" %>
      </div><br/>
    </div>
  </div>
  <br/>
  <%= render 'layouts/task_errors' %>
<% end %>

app/views/tasks/index.html.erb
<h1> <%= @category.category_name %> : Task List </h1>

<table class="table table-bordered table-hover">
   <thead class="table-dark">
    <tr>
      <th class="text-nowrap"> Task </th>
      <th class="text-nowrap"> Details </th>
      <th class="text-nowrap"> Date Created </th>
      <th class="text-nowrap"> Date Updated </th>
      <th class="text-nowrap"> Deadline  </th>
      <th class="text-nowrap"> Status </th>
      <%# <th></th> %>
    </tr>
  </thead>

  <tbody>
    <% @tasks.each do |task| %>
    <% if task.user == current_user %>
      <tr>
        <td class="text-nowrap"> <%= link_to task.task_name, category_task_path(task.category_id, task.id) %> </td>
        <td> <%= task.task_body%> </td>
        <td class="text-nowrap"> <%= task.created_at %> </td>
        <td class="text-nowrap"> <%= task.updated_at %> </td>
        <td class="text-nowrap"> <%= task.deadline %> </td>
        <td class="text-nowrap"> <%= task.status %> </td>
        <%# <td> %>
          <%# <%= link_to "View Task Details", category_task_path(task.category_id, task.id), class: "btn btn-outline-dark btn-sm" %> 
          <%# <%= link_to "Edit", edit_category_task_path(task.category_id, task.id), class: "btn btn-outline-dark btn-sm" %>
          <%# <%= link_to "Delete", category_task_path(task.category_id, task.id), method: :delete, :data => {:confirm => 'Are you sure you want to delete this task?'}, class: "btn btn-outline-dark btn-sm" %> 
        <%# </td> %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table> 

<p>
  <button class="btn btn-outline-dark btn-sm" type="button" data-bs-toggle="collapse" data-bs-target="#collapseExample" aria-expanded="false" aria-controls="collapseExample">
    Sort Tasks
  </button>
  <%= link_to "Add New Task", new_category_task_path, class: "btn btn-outline-dark btn-sm" %> 
  <%= link_to "Back to Categories", categories_path, class: "btn btn-outline-dark btn-sm" %> 
</p>
<div class="collapse" id="collapseExample">
    <ul class="list-group list-group-horizontal">
      <li class="list-group-item text-nowrap"><%= link_to "View All Tasks", category_tasks_path %></li>
      <li class="list-group-item text-nowrap"><%= link_to "Due Today", :sort => "specific_category_tasks_today"%></li>
      <li class="list-group-item text-nowrap"><%= link_to "Status: On-going", :sort => "specific_category_tasks_ongoing"%></li>
      <li class="list-group-item text-nowrap"><%= link_to "Status: Pending", :sort => "specific_category_tasks_pending"%></li>
      <li class="list-group-item text-nowrap"><%= link_to "Status: Done", :sort => "specific_category_tasks_done"%></li>
      <li class="list-group-item text-nowrap"><%= link_to "Sort By Deadline" %></li>
      <li class="list-group-item text-nowrap"><%= link_to "Sort Tasks by Status", :sort => "task_status" %></li>
    </ul>
</div>

<br/>

app/views/tasks/new.html.erb
<%=  form_with scope: :task, url: category_tasks_path, method: :post, locale: true do |form| %>

  <div class="card">
    <div class="card-header">
      <h1>Create New Task</h1>
    </div>

    <div class="card-body">
      <div class="field form-group">
        <%= form.label :task %>
        <%= form.text_field :task_name, class: "form-control" %>
      </div><br/>

      <div class="field form-group">
        <%= form.label :details %>
        <%= form.text_field :task_body, class: "form-control" %>
      </div><br/>

      <div class="field form-group">
        <% form.label :"User ID" %>
        <%= form.number_field :user_id, id: :task_user_id, class: "form-control", value: current_user.id, type: :hidden %>
      </div>

      <div class="field form-group">
        <%= form.label :deadline %>
        <%= form.date_field :deadline, class: "form-control" %>
      </div><br/>

      <div class="field form-group">
        <%= form.label :"Status" %>
        <div class="form-check">
          <%= form.radio_button :status, 'Pending' %>
          <%= form.label :"Pending", class: "form-check-label", for: "flexRadioDefault1" %>
        </div>

        <div class="form-check">
          <%= form.radio_button :status, 'On-going' %>
          <%= form.label :"On-going", class: "form-check-label", for: "flexRadioDefault1" %>
        </div>

        <div class="form-check">
          <%= form.radio_button :status, 'Done' %>
          <%= form.label :"Done", class: "form-check-label", for: "flexRadioDefault1" %>
        </div>
      </div><br/>
    
      <div class="actions">
        <%= form.submit "Add Task", class: "btn btn-dark" %>
      </div><br/>
    </div>
  </div>
  <br/>
  <%= render 'layouts/task_errors' %>
<% end %>

app/views/tasks/show.html.erb
<div class="card">
  <div class="card-header">
    <h1>Task Details</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Task: </h5>
      <p class="card-text"><%= @task.task_name %></p>
    <h5 class="card-title">Details: </h5>
      <p class="card-text"><%= @task.task_body %></p>
    <h5 class= "card-title"> Deadline: </h5>
      <p class="card-text"><%= @task.deadline %> </p>
    <h5 class= "card-title"> Status: </h5>
      <p class="card-text"><%= @task.status %></p>
    <br/>
    <%= link_to "Edit", edit_category_task_path(@task.category_id, @task.id), class: "btn btn-warning btn-sm" %>
    <%= link_to "Delete", category_task_path(@task.category_id, @task.id), method: :delete, :data => {:confirm => 'Are you sure you want to delete this task?'}, class: "btn btn-danger btn-sm" %>
  </div>
</div>

<br/>


<%= link_to "Back to Task List", category_tasks_path, class: "btn btn-outline-dark btn-sm" %>
<%= link_to "Back to Categories", categories_path, class: "btn btn-outline-dark btn-sm" %>