config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  # root to: 'categories#index'
  
  resources :categories do
    resources :tasks
    # do
    # collection do
    #   get 'due_today'
    # end

    # for this category lang
  end
  get "/tasks/due_today", to: "tasks#due_today"
  # di na need ng category id kasi di naman to kasali sa nested routes
  # nil ang value ng params[:category_id] dito kasi wala naman params na category id yung route na to
  get "/tasks/backlog", to: "tasks#backlog"
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <b><%= link_to "Home", root_path, class: "navbar-brand"%> </b>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <% if user_signed_in? %>
          <li class="nav-item">
            <%= link_to "Categories List", categories_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "What's Due Today?", tasks_due_today_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Backlogs", tasks_backlog_path, class: "nav-link" %>
          <li class="nav-item">
            <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Log In", user_session_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/home/index.html.erb
<%# <h1>Home#index</h1>
<p>Find me in app/views/home/index.html.erb</p> %>
<%# <%= image_tag("youdonote-white.jpg", :alt => "rss feed", :class => "rounded float-end", :size => "500x550") %> 
<% if user_signed_in? %>
  <div class="card bg-white text-dark border-0 float-end">
    <%= image_tag("youdonote-white.jpg", :alt => "rss feed", :class => "rounded float-end", :style => "height:80vh; width:80vw;" ) %>
    <div class="card-img-overlay">
      <br/><br/><br/><br/><br/><br/><br/>
      <h1 class="card-title"> You Do Note: The Web App</h1>
      <%# <%# <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p> %>
      <p class="card-text">Categorize and Organize your tasks!</p>
      <br/>
      <%= link_to "Organize My Lists", categories_path, class: "btn btn-dark btn-lg" %>
    </div>
  </div>

<% else %>
  <div class="card bg-white text-dark border-0 float-end">
    <%= image_tag("youdonote-white.jpg", :alt => "rss feed", :class => "rounded float-end", :style => "height:80vh; width:80vw;" ) %>
    <div class="card-img-overlay">
      <br/><br/><br/><br/><br/><br/>
      <h1 class="card-title"> You Do Note: The Web App</h1>
      <%# <%# <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p> %>
      <p class="card-text">Categorize and Organize your tasks!</p>
      <br/>
      <%= link_to "Get Started!", new_user_registration_path, class: "btn btn-dark btn-lg" %>
    </div>
  </div>
<% end %>