config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # get 'home/index'  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: 'home#index'
  # root to: 'categories#index'
  
  resources :categories do
    resources :tasks
    # do
    # collection do
    #   get 'due_today'
    # end

    # for this category lang
  end
  get "/tasks/due_today", to: "tasks#due_today"
  # di na need ng category id kasi di naman to kasali sa nested routes
  # nil ang value ng params[:category_id] dito kasi wala naman params na category id yung route na to
  get "/tasks/backlog", to: "tasks#backlog"
end

app/models/category.rb
class Category < ApplicationRecord
  # Association
  has_many :tasks
  belongs_to :user

  # Validation
  validates :category_name, presence: true
  validates :category_body, presence: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  # if user is not authenticated, don't let them do anything 
  before_action :authenticate_user!
  # make sure it's the correct user for pages that have edit, update, destroy methods
  before_action :correct_user, only: [:edit, :update, :destroy]

  def index
    @categories = current_user.categories 
    # SELECT categories.* FROM categories WHERE user_id=3
    @tasks = current_user.tasks
    # SELECT tasks.* FROM tasks WHERE category_id=

    # @categories = Category.all
    # @tasks = Task.all
  end

  def show
    @category = current_user.categories.find(params[:id])
    # @category = Category.find(params[:id]) - di nakascope kay current_user so makikita pa din lahat ng categories ng ibang users
  end

  def new
    # @category = Category.new
    
    @category = current_user.categories.build
    # build method same with new but instantiates with the defined association
    # just like new, only instantiates still doesnt save
  end

  def create
    # @category = Category.new(category_params)
    @category = current_user.categories.build(category_params)
    if @category.save
      redirect_to categories_path, notice: 'Category was successfully created.'
    else
      render :new
    end
  end

  def edit
    # @category = Category.find(params[:id])
  end

  def update
    # @category = Category.find(params[:id])

    if @category.update(category_params)
      redirect_to categories_path, notice: 'Category was successfully updated.'
    else
      render :edit
    end
  end

  def destroy
    # @category = Category.find(params[:id])

    @category.destroy
    redirect_to categories_path, notice: 'Category was successfully deleted.'
  end

  def correct_user
    # @user = User.all
    @category = current_user.categories.find_by(id: params[:id]) # find id by primary key
    # if not the correct user
    redirect_to categories_path, notice: "You are not authorized to edit this category." if @category.nil?
  end

  private

  def category_params
    params.require(:category).permit(:category_name, :category_body, :user_id)
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/edit.html.erb
<%=  form_with scope: :category, url: category_path, method: :put, locale: true do |form| %>

  <div class="card">

    <div class="card-header">
      <h1>Edit Category Details</h1>
    </div>

    <div class="card-body">
      <div class="field form-group">
        <%= form.label :Title %>
        <%= form.text_field :category_name, class: "form-control" %>
      </div><br/>
      <div class="field form-group">
        <%= form.label :Description %>
        <%= form.text_field :category_body, class: "form-control" %>
      </div><br/>
      <div class="actions">
        <%= form.submit "Save Changes", class: "btn btn-dark btn-sm" %>
        <%= link_to "Delete Category", category_path(@category.id), method: :delete, :data => {:confirm => 'Are you sure you want to delete this category?'}, class: "btn btn-danger btn-sm" %>
      </div>
    </div>

  </div>

  <br/>
  <%= render 'layouts/category_errors' %>
<% end %>

app/views/categories/index.html.erb
<%# <h1> Categories </h1> %>

<table class="table table-bordered table-hover">
  <thead class="table-dark">
    <tr>
      <th class="text-nowrap"> Category</th>
      <th class="text-nowrap"> Description </th>
      <th class="text-nowrap"> Date Created </th>
      <th class="text-nowrap"> Date Updated </th>
      <%# <th> User ID </th> %>
      <%# <th></th> %>
    </tr>
  </thead>

  <tbody>
    <% @categories.each do |category| %>
    <%# specific user, specific categories %>
      <% if category.user == current_user %> 
      <tr>
        <td class="text-nowrap"> <%= link_to category.category_name, category_path(category.id)%> </td>
        <td> <%= category.category_body%> </td>
        <td class="text-nowrap"> <%= category.created_at %></td>
        <td class="text-nowrap"> <%= category.updated_at %></td>
        <%# <td> <%= category.user_id %> 
        <%# <td>
          <%# <%= link_to "View Details", category_path(category.id), class: "btn btn-outline-dark btn-sm" %>
          <%# <%= link_to "Edit", edit_category_path(category.id), class: "btn btn-outline-dark btn-sm" %> 
          <%# <%= link_to "Delete", category_path(category.id), method: :delete, :data => {:confirm => 'Are you sure you want to delete this category?'}, class: "btn btn-outline-dark btn-sm" %> 
        <%# </td> %>
      </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<%= link_to "Add New Category", new_category_path, class: "btn btn-outline-dark btn-sm" %>

app/views/categories/new.html.erb
<%=  form_with scope: :category, url: categories_path, method: :post, locale: true do |form| %>

  <div class="card">
    <div class="card-header">
      <h1> Add New Category </h1>
    </div>

    <div class="card-body">

      <div class="field form-group">
        <%= form.label :category_title %>
        <%= form.text_field :category_name, class: "form-control" %>
      </div><br/>

      <div class="field form-group">
        <%= form.label :description %>
        <%= form.text_field :category_body, class: "form-control" %>
      </div><br/>

      <div class="field form-group">
        <% form.label :user_id %>
        <%= form.number_field :user_id, id: :category_user_id, class: "form-control", value: current_user.id, type: :hidden %>
      </div>

      <div class="actions">
        <%= form.submit "Add New Category", class: "btn btn-dark" %>
      </div><br/>

    </div>
  </div>
    
  <br/>
  <%= render 'layouts/category_errors' %>
<% end %>
    

app/views/categories/show.html.erb
<div class="card">
  <div class="card-header">
    <h1>Category Details</h1>
  </div>
  <div class="card-body">
    <h5 class="card-title">Title: </h5>
    <p class="card-text"><%= @category.category_name %></p>
    <h5 class="card-title">Description: </h5>
    <p class="card-text"><%= @category.category_body %></p>
    <br/>
   
    <%= link_to "Edit", edit_category_path(@category.id), class: "btn btn-warning btn-sm" %>
    <%= link_to "Delete", category_path(@category.id), method: :delete, :data => {:confirm => 'Are you sure you want to delete this category?'}, class: "btn btn-danger btn-sm" %>
    <%= link_to "View Tasks" , category_tasks_path(category_id: @category.id), class: "btn btn-primary btn-sm" %>
  
  </div>
</div>

<br/>

<%= link_to "Back to Categories", categories_path, class: "btn btn-outline-dark btn-sm" %>